project_name: gitmind
before:
  hooks:
    - go mod tidy
builds:
  - id: gitmind
    main: ./cmd/gitmind
    env:
      - CGO_ENABLED=1
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: gitmind
archives:
  - format: tar.gz
    builds: [gitmind]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"